### ISSUE TITLE
Testcase is too weak in B. Pangkat Besar

### ISSUE THREAD

**Issue by 0xwhoami** [ia-toki/tlx-issues#102]
Assalammualaikum
Have a good day!
in this problem https://tlx.toki.id/courses/competitive/chapters/05/problems/B states that any number over 999,999 should print the last 6 digits. I found that my code where A = 1,000,000 and B = 1 output 0 where the output should be 000000, is the accepted code. Please fix this testcase by add a new testcase that i have described above.
Thanks anyway

**Comment by prabowo02** [comment]
This test case has been added

Thanks for the suggestion
