### ISSUE TITLE
Compile Error ketika submit menggunakan Golang

### ISSUE THREAD

**Issue by fakhrizn** [ia-toki/tlx-issues#105]
Ketika submit menggunakan bahasa Go, selalu compile error dengan pesan:
`failed to initialize build cache at /root/.cache/go-build: mkdir /root: permission denied`

Contoh submission yang error: https://tlx.toki.id/courses/competitive/chapters/01/submissions/958515

Contoh kode:
```
package main

func main() {
	// your code goes here
}
```

**Comment by fushar** [comment]
Terima kasih atas laporannya. Sudah diperbaiki.
