### ISSUE TITLE
CompFest 2012 - Final PC Mahasiswa - Problem A (Tim Pekerja) : Typo pada Batasan Soal

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/tlx-issues#111]
[https://tlx.toki.id/problems/compfest-2012-spc-final/A](https://tlx.toki.id/problems/compfest-2012-spc-final/A)

Batasan pada soal menyatakan bahwa salah satu peran pekerja yang mungkin adalah `sekertaris`. Namun peran yang terdapat pada kasus uji adalah `sekretaris` (huruf `r` dan `e` salah posisi).

**Comment by prabowo02** [comment]
Karena soal ini dalam bentuk pdf, kami hanya bisa menambahkan catatan typo.
Terima kasih atas laporannya
