### ISSUE TITLE
ITBPC 2010 - Final Senior - Problem E (Mencari Data): Typo & Kasus Uji Tidak Sesuai Batasan

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/tlx-issues#112]
[https://tlx.toki.id/problems/itbpc-2010-senior-final/E](https://tlx.toki.id/problems/itbpc-2010-senior-final/E)

Deskripsi soal menjelaskan bahwa terdapat tiga perintah:
> Terdapat tiga jenis perintah yaitu: HAPUS x, CARI x.

namun hanya terdapat dua perintah pada deskripsi dan pada kasus uji.

Bilangan awal yang menjadi anggota himpunan tidak unik ([bukti dengan assert](https://tlx.toki.id/problems/itbpc-2010-senior-final/E/submissions/1121886)). Padahal deskripsi soal menyatakan bahwa bilangan yang terdapat pada masukan unik:
> Diberikan himpunan N buah bilangan yang unik dan Q buah perintah.

**Comment by prabowo02** [comment]
Deskripsi sudah diperbaiki:

* "tiga" --> "dua"
* "yang unik" dihapus
