### ISSUE TITLE
GEMASTIK 2021 - Penyisihan Pemrograman - Problem C (Portal dan Monster) : Typo/Kasus Uji Tidak Sesuai Batasan

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/tlx-issues#113]
[https://tlx.toki.id/problems/gemastik-2021-pemrograman-penyisihan/C](https://tlx.toki.id/problems/gemastik-2021-pemrograman-penyisihan/C)

Pada deskripsi soal, batasan untuk nilai `N` adalah `1 ≤ N ≤ 1000`. Namun setelah [dicek menggunakan assert](https://tlx.toki.id/problems/gemastik-2021-pemrograman-penyisihan/C/submissions/1129359), beberapa kasus uji tidak memenuhi batasan soal. Salah satu batasan yang aman untuk nilai `N` adalah `1 ≤ N ≤ 10000`.

**Comment by prabowo02** [comment]
Pada soal ini, nilai N dan K terbesar pada kasus uji yang ada masing-masing adalah 7523 dan 6609

Telah ditambahkan catatan untuk batasan lebih akuratnya
