### ISSUE TITLE
Schematics 2014 - Penyisihan NPC - Problem E (Bibit Unggul) : Kasus Uji Bermasalah

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/tlx-issues#115]
[https://tlx.toki.id/problems/schematics-2014-npc-penyisihan/E](https://tlx.toki.id/problems/schematics-2014-npc-penyisihan/E)

- Nilai `P` pada kasus uji tidak sesuai batasan.
Telah diuji [dengan menambahkan assert](https://tlx.toki.id/problems/schematics-2014-npc-penyisihan/E/submissions/1156472) (line 84 dan 90; `MAXP = 30000`).
- Contoh keluaran tidak sesuai.
Terdapat 3 query pada soal tersebut:
  ! `0 X Y P`: menambahkan `P` kentang ke dalam karung dengan indeks `X` sampai dengan `Y` (inklusif).
  ! `1 X Y P`: menambahkan `f(P, 3)` kentang ke dalam karung dengan indeks `X` sampai dengan `Y` (inklusif), dengan `f(n, k)` adalah indeks kartu terakhir dalam barisan melingkar `n` kartu apabila setiap `k` kartu dikeluarkan ([Josephus problem](https://en.wikipedia.org/wiki/Josephus_problem)).
  ? `2 A B`: menghitung banyaknya kentang untuk setiap karung dengan indeks `A` sampai dengan `B` (inklusif).
Simulasi kasus uji:
Banyaknya kentang pada tiap karung awal: `0 0 0 0 0 0 0`
  - `0 1 4 8`
    `8 8 8 8 0 0 0`
  - `0 4 7 4`
    `8 8 8 12 4 4 4`
  - `0 4 5 3`
    `8 8 8 15 7 4 4`
  - `2 4 6`
    `15 + 7 + 4 = 26`
  - `1 1 6 6`
    `f(6, 3) = 1`
    `9 9 9 16 8 5 4`
  - `0 5 5 10`
    `9 9 9 16 18 5 4`
  - `1 5 6 5`
    `f(5, 3) = 4`
    `9 9 9 16 22 9 4`
  - `2 1 6`
    `9 + 9 + 9 + 16 + 22 + 9 = 74`
Keluaran untuk query terakhir berbeda

**Comment by prabowo02** [comment]
Kasus uji telah diperbaiki
Perhatikan pula bahwa batasan P juga seharusnya 30001 (deskripsi telah diperbaiki juga)
Terima kasih atas laporannya, silakan dibuka kembali isu ini apabila masih bermasalah
