### ISSUE TITLE
Pemrograman Dasar - Ekspresi dan Masukan/Keluaran - Problem D (Bebek untuk Teman) : Typo (?)

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/tlx-issues#116]
[https://tlx.toki.id/courses/basic/chapters/03/problems/D](https://tlx.toki.id/courses/basic/chapters/03/problems/D)

Bagian Petunjuk pada soal ini menyatakan bahwa nilai variabel `sisa` setelah menyimpan hasil dari ekspresi `10 mod 3` adalah `2`, yang seharusnya adalah `1`. Hal lain yang mungkin dapat diganti pada bagian Petunjuk adalah menganti "pascal" dengan "Pascal" dan "c/c++" dengan "C/C++".

**Comment by prabowo02** [comment]
Petunjuk sudah diperbaiki. Terima kasih atas laporannya
