### ISSUE TITLE
Compiled Error menggunakan Golang pada course Pemrograman Dasar "no required module ..."

### ISSUE THREAD

**Issue by Papazy** [ia-toki/tlx-issues#123]
code diketik pada text editor tlx
package main
import "fmt"
func main() {
    fmt.Print("Halo, dunia!")
}
akan tetapi menampilkan compile error :
no required module provides package solution.cpp: go.mod file not found in current directory or any parent directory; see 'go help modules'

**Comment by fushar** [comment]
Mohon maaf atas ketidaknyamanannya. Sudah diperbaiki via https://github.com/ia-toki/judgels/pull/519.
