### ISSUE TITLE
testcase "Paket Soal Latihan TOKI #1 — Problem P27" kurang kuat

### ISSUE THREAD

**Issue by ainunns** [ia-toki/tlx-issues#98]
Pada [soal](https://tlx.toki.id/problems/toki-exercise-1/P27) tidak mengantisipasi [kode](https://tlx.toki.id/submissions/847679) yang memiliki kompleksitas O(N^2) sehingga mendapatkan verdict AC. Testcase yang dapat menggagalkan kode tersebut adalah ketika N=100000, sedangkan isi arraynya terurut tidak menaik. Juga testcase ketika N=100000, sedangkan isi arraynya terurut tidak menurun.

**Comment by prabowo02** [comment]
Test case sudah ditambahkan, bisa dicoba kembali. Terima kasih atas sarannya
